projetFinal/Controllers/EnseignantController.cs
using projetFinal.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projetFinal.Controllers
{
    public class EnseignantController : Controller
    {
        // GET: Enseignant
        public ActionResult Index()
        {
            return View();
        }
   
       // insert new course
        [HttpPost]
        public ActionResult InsertCours(string Nom, string Desc, string Prix,string Cat ,string Niveau)
        {
            DataLinkDataContext db = new DataLinkDataContext();

            cours tmp = new cours
            {
                nomcours = Nom,
                description = Desc,
                prix = double.Parse(Prix),
                nomcat = Cat,
                niveau = Niveau,
                auteur = int.Parse(Session["IdEnseignant"].ToString())
                
            };
            db.cours.InsertOnSubmit(tmp);
            try
            {
                db.SubmitChanges();
            }
            catch (Exception ex)
            {
              
            }

   


            return Json("");
        }
        [HttpPost]
        public ActionResult UpdateCours(string Nom, string Desc, string Prix,string idCours)
        {
            DataLinkDataContext db = new DataLinkDataContext();

            var query =
            from course in db.cours
            where course.Idcours == int.Parse(idCours)
            select course;
            foreach (cours course in query)
            {
                if (Nom != "")
                {
                    course.nomcours = Nom;
                }
            }
            foreach (cours course in query)
            { 
                if (Desc != "")
                {
                    course.description = Desc;
                }
            }
            foreach (cours course in query)
            { 
                if (Prix != "")
                {
                    course.prix = double.Parse(Prix);
                }
            }

            // Submit the changes to the database.
            try
            {
                db.SubmitChanges();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                // Provide for exceptions.
            }
            return Json("");
        }
        public ActionResult UploadFile(string IdCours,string Name,string ext)
        {
            ViewBag.FullName = Name + IdCours+ext;
            ViewBag.idCours = IdCours;
            return View();
        }
        [HttpPost]
        public ActionResult UploadFile(string fullName,string idcours)
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];

                if (file != null && file.ContentLength > 0)
                {
                    var path = Path.Combine(Server.MapPath("~/Upload/"), fullName);
                    file.SaveAs(path);
                }
            }
            ViewBag.liens = getListChapitre(int.Parse(idcours));
            DataLinkDataContext db = new DataLinkDataContext();

            var query =
            from course in db.cours
            where course.Idcours == int.Parse(idcours)
            select course;

            // Execute the query, and change the column values
            // you want to change cours table
                if (fullName.Contains("Notes_"))
                {
                    foreach (cours course in query)
                    {
                        course.notes_cours = fullName;

                    }
                }
                else if(fullName.Contains("Solutions_"))
                {
                    foreach (cours course in query)
                    {
                        course.solutionnaire = fullName;

                    }
                }
                else if (fullName.Contains("Labs_"))
                {
                    foreach (cours course in query)
                    {
                        course.laboratoires = fullName;

                    }
                }
                else if (fullName.Contains("Exercies_"))
                {
                    foreach (cours course in query)
                    {
                        course.exercices = fullName;

                    }
                }
                else if (fullName.Contains("Quiz_"))
                {
                    foreach (cours course in query)
                    {
                        course.quiz = fullName;

                    }
                }
          
         else if (fullName.Contains("Photo_"))
            {
                foreach (cours course in query)
                {
                    course.image = fullName;

                }
            }
            //you want to change chapite table
            else if (fullName.Contains("Video_"))
            {

                chapitre tmp = new chapitre
                {
                    lien = fullName,
                   id_cours = int.Parse(idcours)
                };
                db.chapitre.InsertOnSubmit(tmp);


                try
                {
                    db.SubmitChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.viol_constraint = "your are already enrolled,";

                    return RedirectToAction("ShowDetailCours", new { id = idcours });
                }

                return RedirectToAction("ShowDetailCours", new { id = idcours });


            }
            // Submit the changes to the database.
            try
            {
                db.SubmitChanges();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                // Provide for exceptions.
            }

            return RedirectToAction("ShowDetailCours", new { id = idcours });

        }
        public ActionResult TeacherCorner()
        {
            DataLinkDataContext db = new DataLinkDataContext();
            cours s1 = new cours();
            var requet = from element in db.niveauscolaire
                         select element.niveau;


            ViewBag.niveau = requet;

            var Query = from element in db.categorie
                        select element.nomcat;

            ViewBag.cat = Query;

            var resultat = (from m in db.cours
                            where m.auteur == int.Parse(Session["IdEnseignant"].ToString())
                            select new ClsCours { Id = (m.Idcours).ToString(), Nomcours = m.nomcours, Description = m.description, Nbremodule = m.nbremodule, Prix = (float)m.prix, Image = m.image, Niveau = m.niveau, Categorie = m.nomcat }).ToList();

            return View(resultat);
        }
        public ActionResult ShowDetailCours(string id)
        {
            DataLinkDataContext db = new DataLinkDataContext();
            cours s1 = new cours();
            var resultat = (from m in db.cours
                            where m.Idcours == Int32.Parse(id)
                            select new ClsCours { Id = (m.Idcours).ToString(), Nomcours = m.nomcours, Description = m.description, Nbremodule = m.nbremodule, Prix = (float)m.prix, Image = m.image, Niveau = m.niveau, Notescours = m.notes_cours, Solutionnaires = m.solutionnaire, Laboratoires = m.laboratoires, Exercices = m.exercices, Quiz = m.quiz }).Single<ClsCours>();
            var NbEtudiant = (from m in db.etudiantcours
                              where m.idcours == Int32.Parse(id)
                              select m).Count();
            ViewBag.NbEtudiant = NbEtudiant.ToString();
            ViewBag.liens = getListChapitre(int.Parse(id));
            ViewBag.NbCours = ViewBag.liens.Count;
           
            return View(resultat);
        }
        public ActionResult Chat(string loginreciever)
        {
            Session["lastRecordId"] = 0;
            DataLinkDataContext db = new DataLinkDataContext();
            student s = new student();
            var resultat = (from m in db.student
                            from ec in db.etudiantcours
                            from c in db.cours
                            where c.auteur == int.Parse(Session["IdEnseignant"].ToString())
                            && ec.idcours == c.Idcours
                            && ec.idetudiant==m.Id    
                            select new ClsEtudiant { IdEtudiant = m.Id, LoginEtudiant = m.login }).ToList();
            ViewBag.listLogins = resultat;
            ViewBag.loginreciever = loginreciever;

            return View();
        }
        [HttpPost]
        public ActionResult ChatMessage(string MsgText, int id, string to)
        {
            DataLinkDataContext db = new DataLinkDataContext();
            string loginEnseignant = (string)Session["LoginEnseignant"];
            if (id != 0)
            {
                id = (int)Session["lastRecordMsg"];
            }
            conversations cnv = new conversations
            {

                login_sender = loginEnseignant,
                login_reciever = to,
                date_inscrit = DateTime.Now,
                contenu = MsgText
            };
            if (cnv.contenu != "")
            {
                db.conversations.InsertOnSubmit(cnv);
                try
                {
                    db.SubmitChanges();
                }
                catch (Exception ex)
                {
                    ViewBag.viol_constraint = "your are already enrolled,";
                }
            }
            else
            {

                var req1 = from m in db.conversations
                           where
                           m.login_reciever == cnv.login_reciever
                           &&
                           m.login_sender == cnv.login_sender
                           orderby m.Id descending
                           select m;

projetFinal/Views/Enseignant/Chat.cshtml
@{
    ViewBag.Title = "Chat";
    ViewBag.Title = "ChatMessage";
    Layout = "~/Views/Enseignant/_LayoutEnseignant.cshtml";
    string active = " active ";
}
<link href="~/Style/chatStyle.css" rel="stylesheet" />
<div class="container p-4">
    <div class="row rounded-lg overflow-hidden shadow">
        <div class="col-5 px-0 bg-white">
            <div class="bg-gray px-4 py-2 bg-info">
                <p class="h5 mb-0 py-1">Users</p>
            </div>
            <div class="messages-box">
                <div class="list-group rounded-0">
                    @foreach (var element in ViewBag.listLogins)
                    {
                        <a class="list-group-item list-group-item-action @if (ViewBag.loginreciever==element.LoginEtudiant) { @active; }rounded-0" href="@Url.Action("Chat","Enseignant", new { loginreciever = element.LoginEtudiant })">
                            <div class="media active">
                                <img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle">
                                <div class="media-body ml-4">
                                    <div class="d-flex align-items-center justify-content-between mb-1">
                                        <h6 class="mb-0">@element.LoginEtudiant</h6>
                                    </div>
                                    <p class="font-italic mb-0 text-small"></p>
                                </div>
                            </div>
                        </a>
                    }
                </div>
            </div>
        </div>
        <div class="col-7 px-0 bg-white">
            <form action="#" class="bg-light m-0">
                <div class="input-group">
                    <input type="text" placeholder="Type a message" aria-describedby="button-addon2" class="form-control rounded-0 border-0 py-4 m-0 bg-light" id="MessageArea">
                    <div class="input-group-append">
                        <button type="button" id="Send" class="btn btn-link"> <i class="fa fa-paper-plane"></i></button>
                    </div>
                </div>
            </form>
            <div class="px-4 py-5 chat-box bg-white" id="messageSection">

            </div>
        </div>
    </div>
</div>
<script>
    load2("", 0);
    const out = document.getElementById("messageSection")
    let c = 0
    $('#Send').click(function () {
        load2($("#MessageArea").val(), 1);
        $('#MessageArea').val("");
    });
    setInterval(function () {
        load2("", 1);
    }, 500);
    function load2(Msg, id) {
        $.ajax({
            url: '/Enseignant/ChatMessage',
            type: 'POST',
            dataType: 'json',
            data: { MsgText: Msg, id: id, to: '@ViewBag.loginreciever' },
            success: function (data) {
                for (var element = 0 in data) {
                    if ('@Session["LoginEnseignant"]' != data[element].loginsender) {
                        $("#messageSection").prepend('<div class="media w-50 mb-3"><img src="https://res.cloudinary.com/mhmd/image/upload/v1564960395/avatar_usae7z.svg" alt="user" width="50" class="rounded-circle"><div class="media-body ml-3 "><div class="bg-light rounded py-2 px-3 mb-2"> <p class="text-small mb-0 text-muted">' + data[element].contenu + '</p></div><p class="small text-muted">'+formaterDate(data[element].dateinscrit)+'</p></div></div>')
                    }
                    else {
                        $("#messageSection").prepend('<div class="media w-50 ml-auto mb-3"><div class="media-body"><div class="bg-primary rounded py-2 px-3 mb-2"><p class="text-small mb-0 text-white">' + data[element].contenu + '</p></div><p class="small text-muted">'+formaterDate(data[element].dateinscrit)+'</p></div></div>')
                    }
                }
                }, error: function (data) {
                    alert(data.error);
                }
        });
    }
    function formaterDate(date) {
        var nowDate = new Date(parseInt(date.substr(6)));
        return nowDate.getDate() + "/" + nowDate.getMonth() + "/" + nowDate.getFullYear() + " | " + nowDate.getHours() + ":" + nowDate.getMinutes() ;
    }
    $( document ).ready(function() {
	  $('#accueil').removeClass( "bg-light" );
	  $('#chat').addClass( "bg-light" );
	});
</script>

projetFinal/Views/Enseignant/ShowDetailCours.cshtml
@model projetFinal.Models.ClsCours
@{
    ViewBag.Title = "ShowDetailCours";
    ViewBag.Title = "TeacherCorner";
    Layout = "~/Views/Enseignant/_LayoutEnseignant.cshtml";
    HttpContext.Current.Session["lastRecordId"] = 0;
    int i = 1;

}
<link href="~/Style/ShowDetailCours.css" rel="stylesheet" />
<div class="container-fluid">
    <div class="row py-4 bg-light rounded">
        <div class="col-12 ">
            <button onclick="edit()" class="btn fa fa-4x fa-edit pull-right"></button>
        </div>
        <div class="col-sm-4 col-xs-6 ">
            <img src="~/images/@Html.DisplayFor(model => model.Image)" alt="" class="img-thumbnail">
        </div>
        <div class="col-sm-8 col-xs-6 ">
            <h1 style="text-shadow: 2px 2px 4px gray;" id="nom">@Html.DisplayFor(model => model.Nomcours)</h1>
            <p id="desc">
                <i>
                    @Html.DisplayFor(model => model.Description)
                </i>
            </p>
            <p>
                <span class="text-muted">@Html.DisplayFor(model => model.Niveau)</span>
                <br />
                @ViewBag.NbCours Courses
                <br />
                @ViewBag.NbEtudiant Etudiants
                <br />
                <b id="prix">
                    <i>@Html.DisplayFor(model => model.Prix) $CAD</i>
                </b>
            </p>
            <div id="infos"></div>
        </div>
    </div>
    <div class="row bg-light">
        <div class="col-sm-9 col-xs-12 ">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" id="myFrame" src=""></iframe>
            </div>
        </div>
        <div class="col-sm-3 col-xs-12 " style="max-height: 100vh;overflow:auto;-webkit-overflow-scrolling: touch;">
            <div class="list-group bg">
                <button class="list-group-item bg-dark text-center btn text-light fa fa-2x fa-plus" onclick='window.location.href="@Url.Action("UpLoadFile","Enseignant", new { idCours = @Html.DisplayFor(model => model.Id),Name="Video_",ext=".mp4" }, null)"'></button>
                @foreach (string element in ViewBag.liens)
                {
                    <button class="list-group-item btn btn-primary text-dark" onclick="changeCours('~/Upload/@element',this)">Chapitre @i</button>
                    i++;
                }
                <button class="list-group-item bg-dark text-center btn text-light fa fa-2x fa-plus"></button>
            </div>
        </div>
    </div>
    <div class="row bg-light">
        <div class="col-sm-9 col-xs-12 mb-2 mt-2">
            <button class="btn" style="color:royalblue;" onclick='window.location.href="@Url.Action("UpLoadFile","Enseignant", new { idCours = @Html.DisplayFor(model => model.Id),Name="Notes_",ext=".pdf" }, null)"'><i class="fa fa-upload"></i> Notes de cours</button>
            <button class="btn" style="color:green;" onclick='window.location.href="@Url.Action("UpLoadFile","Enseignant", new { idCours = @Html.DisplayFor(model => model.Id),Name="Solutions_",ext=".pdf" }, null)"'><i class="fa fa-upload"></i> Solutionnaires</button>
            <button class="btn" onclick='window.location.href="@Url.Action("UpLoadFile","Enseignant", new { idCours = @Html.DisplayFor(model => model.Id),Name="Labs_",ext=".pdf" }, null)"'><i class="fa fa-upload"></i> Laboratoires</button>
            <button class="btn" onclick='window.location.href="@Url.Action("UpLoadFile","Enseignant", new { idCours = @Html.DisplayFor(model => model.Id),Name="Exercies_",ext=".pdf" }, null)"'><i class="fa fa-upload"></i> Exercices</button>
            <button class="btn" onclick='window.location.href="@Url.Action("UpLoadFile","Enseignant", new { idCours = @Html.DisplayFor(model => model.Id),Name="Quiz_",ext=".pdf" }, null)"'><i class="fa fa-upload"></i> Quiz</button>
            <button class="btn" onclick='window.location.href="@Url.Action("UpLoadFile","Enseignant", new { idCours = @Html.DisplayFor(model => model.Id),Name="Photo_",ext=".jpg" }, null)"'><i class="far fa-image"></i> Change photo</button>
        </div>
    </div>
</div>
<script>
 
    function changeCours(lien,btn) {
        $('#myFrame').attr('src', lien);
        $('.list-group button').removeClass("active");
        $(btn).addClass("active");
    }
    function edit() {

        $('#nom').html('<input id="nomCours" type="text" class="form-control rounded-0"  placeholder="Title..." >');
        $('#desc').html('<textarea id="desCours" class="form-control rounded-0" rows="4" placeholder="Description..."></textarea>');
        $('#prix').html('<input id="prixCours" type="number" step="any" class=" rounded-0"  placeholder="Price..." >$');
        $('#infos').html('<button class="btn btn-success btn-lg" onclick="update()"><i class="fa fa-save"></i>Save</button><button class="btn btn-danger btn-lg mx-3" onclick="unedit()"><i class="fa fa-times"></i> Cancel</button>');
    }
   // function unedit bloque le script probleme de syntax
      @*function unedit() {
        $('#nom').html('@Html.DisplayFor(model => model.Nomcours)');
        $('#desc').html('<i>@Html.DisplayFor(model => model.Description)</i>');
        $('#prix').html('<i>@Html.DisplayFor(model => model.Prix)$CAD</i>');
        $('#infos').html('');
    

    }*@


    function update() {


        var nom = $('#nomCours').val();
        var desc = $('#desCours').val();
        var prix = $('#prixCours').val();
        $.ajax({
            url: '/Enseignant/UpdateCours',
            type: 'POST',
            dataType: 'json',
            data: { Nom: nom, Desc: desc, Prix:prix,idCours:'@Html.DisplayFor(model => model.Id)'},
            success: function (data) {
               
              //display seccess message to the DOM
                alert('update ok');
                }, error: function (data) {
                    alert(data.error);
                }
        });
    }
  
</script>

projetFinal/Views/Enseignant/TeacherCorner.cshtml
@model IEnumerable<projetFinal.Models.ClsCours>
@{
    ViewBag.Title = "studentCorner";
    ViewBag.Title = "Index";
    ViewBag.Title = "ShowDetailCours";
    ViewBag.Title = "_LayoutEnseignant";
    Layout = "~/Views/Enseignant/_LayoutEnseignant.cshtml";
}
<link href="~/Style/StudentCornerStyle.css" rel="stylesheet" />
<div class="row text-white">
    <div class="col-12 input-group">
        <h2 class="h1 ml-3 mr-5">List Of My Courses</h2>
        <button type="button" class="btn btn-info  " data-toggle="collapse" href="#collapseAdd" role="button" aria-expanded="false" aria-controls="collapseExample"><i class="fa fa-plus"></i> Add New</button>
    </div>
    <div class="collapse row" id="collapseAdd">
        <div class="container bg-light m-5 p-5 rounded">
            <div class="container-fluid">
                <div class="col-12">
                    <div class="md-form mt-0">
                        <div class='division text-center text-dark'>
                            <big><b>Add a Course</b></big>
                            <hr class='mb-4'>
                        </div>
                        <input type="text" class='form-control my-1' id="NomCours" name='NomCours' placeholder="Title" required>
                        <textarea rows="4" class='form-control my-1' id="Desc" name='Description' placeholder="Description..." required></textarea>
                        <input type="number" class='form-control my-1' id="prixCours" step="any" name='Prix' placeholder="Price $CAD" required>
                        <select class="form-control my-2" id="selectCat" name="Niveau">
                            @foreach (string element in ViewBag.cat)
                            {
                                <option value="@element">@element</option>
                            }
                        </select>
                        <select class="form-control my-2" id="selectedNiveau" name="Niveau">
                            @foreach (string element in ViewBag.niveau)
                            {
                                <option value="@element">@element</option>
                            }
                        </select>
                      
                    </div>
                </div>
            
                <button onclick="insert()" class="btn btn-success fa fa-plus mx-3">ADD</button>
            </div>
        </div>

    </div>
</div>
<div class="row text-white py-4 mb-4">
    @foreach (var item in Model)
    {
        <div class="col-md-3 col-sm-3 col-xs-6 mt-5 d-flex align-items-stretch" title="@Html.DisplayFor(modelItem => item.Prix) $CAD" data-html="true" data-content="<div class='row mb-4'>
                    <div class='col-sm-4 col-xs-6'>
                        @*change url from images folder to upload folder*@ 
                    <img src='/images/@Html.DisplayFor(modelItem => item.Image)' alt=' image' class='img-fluid'>
                    </div>
                    <div class='col-sm-8 col-xs-6'>
                        <h1 style='text-shadow: 2px 2px 4px gray;'>@Html.DisplayFor(modelItem => item.Nomcours)</h1>
                    <p>@Html.DisplayFor(modelItem => item.Nbremodule) Courses
                    </div>
                    </div>" data-toggle="popover" data-placement="right" data-trigger="hover"  onclick='window.location.href="@Url.Action("ShowDetailCours","Enseignant", new { id = @Html.DisplayFor(modelItem => item.Id) }, null)"'>
					<div class="card shadow">
						<img class="card-img-top img-fluid" src="~/images/@Html.DisplayFor(modelItem => item.Image)" alt="Card image cap">
						<div class="card-block m-4">
                            <h4 class="card-title m-2 mb-2 text-dark">@Html.DisplayFor(modelItem => item.Nomcours)</h4>
							<span class="card-text m-2"><i><big><font color="red">@Html.DisplayFor(modelItem => item.Nbremodule) Courses</font></big></i></span>
						</div>
					</div>
			</div>
    }
</div>
<script>
    /* $(document).ready( function() {
         $(document).on('change', '.btn-file :file', function() {
         var input = $(this),
             label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
         input.trigger('fileselect', [label]);
         });

         $('.btn-file :file').on('fileselect', function(event, label) {

             var input = $(this).parents('.input-group').find('#form-control'),
                 log = label;

             if( input.length ) {
                 input.val(log);
             } else {
                 if( log ) alert(log);
             }

         });
         function readURL(input) {
             if (input.files && input.files[0]) {
                 var reader = new FileReader();

                 reader.onload = function (e) {
                     $('#img-upload').attr('src', e.target.result);
                 }

                 reader.readAsDataURL(input.files[0]);
             }
         }

         $("#imgInp").change(function(){
             readURL(this);
         });
     });*/
    //***********if you need to get the file name or change it you may need some parts of this

   
    function insert() {

    
        var nom = $('#NomCours').val();
        var desc = $('#Desc').val();
        var prix = $('#prixCours').val();
        var niveau = $('#selectedNiveau').find(":selected").text();
        var cat = $('#selectCat').find(":selected").text();


        $.ajax({
            url: '/Enseignant/InsertCours',
            type: 'POST',
            dataType: 'json',
            data: { Nom: nom, Desc: desc, Prix: prix, Cat: cat, Niveau: niveau },
            success: function (data) {
               
                //display seccess message to the DOM
                alert('insert ok');
            }, error: function (data) {
                alert(data.error);
            }
        });

    }
</script>

projetFinal/Views/Enseignant/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
    Layout = "~/Views/Enseignant/_LayoutEnseignant.cshtml";
}

<h2>Upload File</h2>
<body>
    @using (Html.BeginForm("UploadFile", "Enseignant", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <input type="file" name="file"  />
        <input type="hidden" name="fullName" value="@ViewBag.fullName" />
        <input type="hidden" name="idCours" value="@ViewBag.idCours" />
        <input type="submit" value="LOAD" />
    }
</body>

projetFinal/Views/Enseignant/_LayoutEnseignant.cshtml
<html>
@RenderSection("scripts", required: false)
@{
    ViewBag.Title = "Index";
}
<head>
    <title>THOT</title>
    <meta charset="utf-8">
    <link href="~/Style/LayoutStyle.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Content/popper.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="~/Content/bootstrap.min.js"></script>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/style/MyStyleSheet.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
</head>
<body data-spy="scroll" data-target=".navbar" data-offset="50" class="bg-light">
    <div class="vertical-nav bg-white" id="sidebar">
        <div class="nav-item dropdown py-4 px-3 mb-4 bg-light">
            <div class="media d-flex align-items-center">
                <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" alt="..." width="65" class="mr-3 rounded-circle img-thumbnail shadow-sm">
                <div class="media-body">
                    <h4 class="m-0">@Session["FullName"]</h4>
                    <div class="dropdown-menu dropdown-menu-right mt-2" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#"><i class="fa fa-eye mr-2"></i> View profile</a>
                        <a class="dropdown-item" href="#"><i class="fa fa-edit mr-2 text-info"></i> Edit</a>
                        <a class="dropdown-item" href="index.html"><i class="fa fa-sign-out mr-2 text-danger"></i> Log out</a>
                    </div>
                </div>
            </div>
        </div>
        <p class="text-gray font-weight-bold text-uppercase px-3 small pt-4 mb-0">Main</p>
        <ul class="nav flex-column bg-white mb-0">
            <li class="nav-item">
                <a href="@Url.Action("TeacherCorner","Enseignant")" id="accueil" class="nav-link bg-light text-dark font-italic ">
                    <i class="fa fa-th-large mr-3 text-primary fa-fw"></i>
                    <big>Home</big>
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("Chat","Enseignant", new { idreciever = Session["IdEnseignant"] })" id="chat" class="nav-link text-dark font-italic">
                    <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
                    <big>Chat room</big>
                </a>
            </li>
        </ul>
    </div>
    <div class="page-content p-4 " id="content">
        <div class="row rounded-top" id="toprow">
            <div class="col-12">
                <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4 sticky-top">
                    <i class="fa fa-bars my-1 mr-2"></i>
                    <small class="text-uppercase font-weight-bold">Menu</small>
                </button>
            </div>
        </div>
        @RenderBody()
        <button id="sidebarCollapse2" type="button" class="btn btn-light bg-white rounded-pill shadow-sm px-4 mb-4 fixed-bottom">
            <i class="fa fa-bars"></i>
        </button>
        <footer class="sticky-bottom bg-light" id="downrow">
            <center>&copy; @DateTime.Now.Year - THOT .Co</center>
        </footer>
    </div>
    <script>
        $(document).ready(function () {
            $('[data-toggle="popover"]').popover();
        });
        $(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
            });
            $('#sidebarCollapse2').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
            });
        });
    </script>
</body>
</html>